package POJO;
// Generated 04-jun-2015 19:06:18 by Hibernate Tools 4.3.1





/**
 * Votante generated by hbm2java
 */


public class Votante  implements java.io.Serializable {


     private Integer idVotante;
     private String nif;
     private String password;
     private String votado;

    public Votante() {
    }

	
    public Votante(String votado) {
        this.votado = votado;
    }
    public Votante(String nif, String password, String votado) {
       this.nif = nif;
       this.password = password;
       this.votado = votado;
    }
   
    public Integer getIdVotante() {
        return this.idVotante;
    }
    
    public void setIdVotante(Integer idVotante) {
        this.idVotante = idVotante;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getVotado() {
        return this.votado;
    }
    
    public void setVotado(String votado) {
        this.votado = votado;
    }




}


